#! /bin/bash

set -o xtrace

if [[ "${OSTYPE}" == "linux-gnu" ]]; then
    # ------------
    # ag
    # ------------
    AG="$(which "ag")"
    if [ $? -ne 0 ]; then
        sudo apt-get install "silversearcher-ag"
    fi

    # ------------
    # python-pip
    # ------------
    PIP="$(dpkg -s "python-pip" >/dev/null)"
    if [[ "$?" -ne 0 ]]; then
        sudo apt-get install "python-pip"
    fi
    pip install --upgrade pip

    # ------------
    # neovim
    # ------------
    pip2 install --upgrade --user neovim
    NVIM="$(which "nvim")"
    if [[ "$?" -ne 0 ]]; then
        curl -o ~/bin/nvim -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        chmod u+x ~/bin/nvim
    fi

    # ------------
    # fzf
    # ------------
    FZF="$(which "fzf")"
    if [ $? -ne 0 ]; then
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
            ~/.fzf/install
    fi
elif [[ "${OSTYPE}" == "darwin"* ]]; then
    # ------------
    # ag
    # ------------
    AG="$(which "ag")"
    if [ $? -ne 0 ]; then
        brew install ag
    fi

    # ------------
    # fzf
    # ------------
    FZF=$(which "fzf")
    if [ $? -ne 0 ]; then
        brew install fzf

        # Install shell extensions
        /usr/local/opt/fzf/install
    fi
fi

mkdir -p "~/bin"

# neovim




# .vim
git submodule update --init --recursive

# .files
ln -sf ~/.vim/vimrc ~/.vimrc
ln -sf ~/.vim/gvimrc ~/.gvimrc
ln -sf ~/.files/inputrc ~/.inputrc
ln -sf ~/.files/tmux.conf ~/.tmux.conf
ln -sf ~/.files/jshintrc ~/.jshintrc
ln -sf ~/.files/ackrc ~/.ackrc
ln -sf ~/.files/htoprc ~/.htoprc
ln -sf ~/.files/gitconfig ~/.gitconfig
ln -sf ~/.files/gitignore ~/.gitignore
