#! /bin/bash

set -o xtrace

# --- ag
AG=$(which ag)
if [ $? -ne 0 ]; then
    brew install ag
fi
# ---

# --- fzf
FZF=$(which fzf)
if [ $? -ne 0 ]; then
    brew install fzf

    # Install shell extensions
    /usr/local/opt/fzf/install
fi
# ---

git submodule init;
git submodule update;

cd .files; ./bootstrap.sh; cd ../;
cd .vim; ./bootstrap.sh; cd ../;
