#! /bin/bash

set -o xtrace

if [[ "${OSTYPE}" == "linux-gnu" ]]; then
    # ------------
    # ag
    # ------------
    AG="$(which ag)"
    if [ $? -ne 0 ]; then
            sudo apt-get install "silversearcher-ag"
    fi

    # ------------
    # fzf
    # ------------
    FZF="$(which fzf)"
    if [ $? -ne 0 ]; then
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
            ~/.fzf/install
    fi
elif [[ "${OSTYPE}" == "darwin"* ]]; then
    # ------------
    # ag
    # ------------
    AG=$(which ag)
    if [ $? -ne 0 ]; then
        brew install ag
    fi

    # ------------
    # fzf
    # ------------
    FZF=$(which fzf)
    if [ $? -ne 0 ]; then
        brew install fzf

        # Install shell extensions
        /usr/local/opt/fzf/install
    fi
fi

# .vim
git submodule update --init --recursive

# .files
ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc
ln -sf ~/.files/inputrc ~/.inputrc
ln -sf ~/.files/tmux.conf ~/.tmux.conf
ln -sf ~/.files/jshintrc ~/.jshintrc
ln -sf ~/.files/ackrc ~/.ackrc
ln -sf ~/.files/htoprc ~/.htoprc
ln -sf ~/.files/gitconfig ~/.gitconfig
ln -sf ~/.files/gitignore ~/.gitignore
