#!/bin/sh

alias ga='git add'
alias gb='git branch'
alias gbd='git branch -D'
alias gc='git commit -v'
alias go='git checkout'
alias gob='git checkout -B'
alias gd='git diff --color'
alias gh='git --no-pager log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short -20'
alias gi='git commit -av'
alias gl='git pull --rebase'
alias glrm='git pull --rebase origin master'
alias gp='git push origin'
alias gpm='git push origin master'
alias gs='git status'
